### PR TITLE
fixing #4 Updated the button text from "Scrape Submission" to "Get Submission" for better clarity

### PR DESCRIPTION
**Pull request by adilkadivala**
* [`src/app/page.js`](diffhunk://#diff-e7e49cbc2b5fe144cd9f7428f05b4cfe87d5b0725f24282930df6917ea5e0d2dL201-R200): Updated the button text from "Scrape Submission" to "Get Submission" for better clarity Submission Retrieval #4

### CODE REVIEW

**Comment by shuklamaneesh23** [comment]
Hey @adilkadivala, thanks for your contribution! However, it seems that this PR addresses multiple problems in one go. Kindly ensure that each PR focuses on solving a single issue to keep things organized and easier to review.

Additionally, please get the issue assigned to you before submitting a PR. You can do this by commenting on the issue you plan to work on and waiting for it to be assigned. Once the issue is assigned, feel free to submit a PR for it.

Looking forward to your updated contributions!

Thanks again! 😊

**Comment by shuklamaneesh23** [comment]
Dear @adilkadivala, please let me know if you're still working on this issue. If so, kindly reply within the next 24 hours. Also, please ensure that you solve only issue #4 using this PR, as that is the one assigned to you.

Don't forget to update the PR title and description to reflect the correct issue. Looking forward to your response and updates!

**Comment by adilkadivala** [comment]
Hi @shuklamaneesh23 ,  I'm working on #4 and i have already fix it,  let me change the PR description.. and kindly please label this issue with **hacktoberfest** or **hacktoberfest-accepted**..

**Comment by shuklamaneesh23** [comment]
Here's the updated version of your feedback, incorporating the additional points:

---

**Feedback on PR:**

Hey @adilkadivala,

Thanks for your work on the PR! However, I noticed a few things that need to be corrected:
- The commit message and PR title shouldn't contain the issue hash or my username tag.
- Please pull the latest commits from the repo before making changes to avoid merge conflicts.
- Dont change the unnecessary lines of code that are not linked with your issue.
- Only change the button text, a single line change is needed.
- If you found any other issue, just raise it up!.We are open for new issues.

Additionally:
- I'm closing this PR for now. You can make a new one once the necessary changes are made.
- As you asked about the Hacktoberfest label, just a heads-up: the issue already has the Hacktoberfest tag, but the PR doesn't automatically get it. Once your updated PR meets the expected results, I'll add the `hacktoberfest-accepted` label and proceed with the merge.

Let me know if you need any help!

**Comment by shuklamaneesh23** [comment]
Hey @adilkadivala,

Thanks for your work on the PR! However, I noticed a few things that need to be corrected:
- The commit message and PR title shouldn't contain the issue hash or my username tag.
- Please pull the latest commits from the repo before making changes to avoid merge conflicts.
- Dont change the unnecessary lines of code that are not linked with your issue.
- Only change the button text, a single line change is needed.
- If you found any other issue, just raise it up!.We are open for new issues.

Additionally:
- I'm closing this PR for now. You can make a new one once the necessary changes are made.
- As you asked about the Hacktoberfest label, just a heads-up: the issue already has the Hacktoberfest tag, but the PR doesn't automatically get it. Once your updated PR meets the expected results, I'll add the `hacktoberfest-accepted` label and proceed with the merge.

Let me know if you need any help!

**Pull request closed without merging**
