### PR TITLE
updated the default metadata and title

### LINKED ISSUE #10: The meta data, title and favicon were default of next Js
image

the project is using the default meta data title and favicon provided by next js this needs to be fixed

### PR DESCRIPTION
**Pull request by JaiSharma1710**
**Fixes #10**

- Updated the metadata, title, and favicon to reflect the project-specific branding instead of the default NestJS configurations.
- Renamed `env.example` file to follow industry-standard naming conventions for better clarity and alignment with best practices.

Updated Metadata Screenshot

---

### CODE REVIEW

**Comment by shuklamaneesh23** [comment]
Good work @JaiSharma1710! Please revise your PR description to ensure it's grammatically correct. Also, make sure to define the process clearly before adding the screenshot. This will help maintain clarity and make your contribution more professional.

Thanks!

**Comment by JaiSharma1710** [comment]
> Good work @JaiSharma1710! Please revise your PR description to ensure it's grammatically correct. Also, make sure to define the process clearly before adding the screenshot. This will help maintain clarity and make your contribution more professional.
> 
> Thanks!

@shuklamaneesh23 thank you for the suggestion updated the same as requested

**Comment by JaiSharma1710** [comment]
hi @shuklamaneesh23  and @yatinsharmaa12  can you guys please close this pr if possable.

**Comment by shuklamaneesh23** [comment]
@JaiSharma1710, everything looks good except for the renaming of env.sample. Please leave it as it is. Once you're done, let me know.

Thanks!

**Comment by JaiSharma1710** [comment]
> @JaiSharma1710, everything looks good except for the renaming of env.sample. Please leave it as it is. Once you're done, let me know.
> 
> Thanks!

@shuklamaneesh23  done.

**Comment by shuklamaneesh23** [comment]
Great @JaiSharma1710 ,I am closing this PR now by merging it into master branch.
Thanks for the contribution.

**Pull request merged**
